version: '3.1'

services:

  nginx-proxy-manager:
    container_name: nginx
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      # Mysql/Maria connection parameters:
      DB_MYSQL_HOST: "npm_db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - npm_db
    networks:
      - npm_db_network
      - web_network


  npm_db:
    container_name: npm_db_container
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - npm_db:/var/lib/mysql
    networks:
      - npm_db_network


  wordpress:
    depends_on:
      - wp_db
    container_name: wordpress
    image: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: wp_db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wpdb
    volumes:
      - ./PetWeb-Template:/var/www/html/wp-content/themes/PetWeb-Template
      - wordpress:/var/www/html
    networks:
      - web_network
      - wp_db_network


  wp_db:
    container_name: wp_db_container
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: wpdb
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - wp_db:/var/lib/mysql
    networks:
      - wp_db_network


volumes:
  wordpress:
  wp_db:
  npm_db:

networks:
  web_network:
  wp_db_network:
  npm_db_network: